### ISSUE TITLE
主机密码设置错误

### ISSUE THREAD

**Issue by heaquan** [Joshuapy/ansible2_myAPI#6]
Traceback (most recent call last):
  File "/home/xxx/Network/scms/ansible-test.py", line 14, in <module>
    result = runner.run()
  File "/home/xxx/Network/scms/ansible2_myAPI/runner.py", line 158, in run
    raise Exception(e)
Exception: 'str' object has no attribute 'get'

提示这个错误呢？什么原因呢

from ansible2_myAPI.runner import Runner

runner = Runner(
	module_name="shell",
    module_args="uptime",
    remote_user="test",
    pattern="all",
    hosts="172.19.0.70, ",
    passwords='123'

)

result = runner.run()

**Comment by Joshuapy** [comment]
用sshkey的方式试下 别用密码
